# Generated by Django 3.2.8 on 2021-10-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('cod_art', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('descrip_art', models.CharField(max_length=100)),
                ('stock_mat', models.FloatField()),
                ('stock_bul', models.FloatField()),
                ('stock_bod', models.FloatField()),
                ('cant_vent', models.FloatField()),
                ('min_mat', models.IntegerField()),
                ('min_bul', models.IntegerField()),
                ('min_bod', models.IntegerField()),
                ('familia', models.CharField(max_length=50)),
                ('subcat1', models.CharField(max_length=50)),
                ('subcat2', models.CharField(max_length=50)),
                ('subcat3', models.CharField(max_length=50)),
                ('ult_pre_comp', models.FloatField()),
                ('stock_fut', models.FloatField()),
                ('rep_min', models.FloatField()),
                ('rep_max', models.FloatField()),
                ('id_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proveedor')),
            ],
        ),
    ]
