# Generated by Django 3.2.3 on 2021-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='cant_vent',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='min_bod',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='min_bul',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='min_mat',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='rep_max',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='rep_min',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock_bod',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock_bul',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock_fut',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock_mat',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcat1',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcat2',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcat3',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='ult_pre_comp',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descrip_art',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
