# Generated by Django 3.2.3 on 2021-11-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211101_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock_bod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
