# Generated by Django 3.2.3 on 2021-11-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stockminimoproductos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockminimoproductos',
            old_name='stock_bod',
            new_name='min_bod',
        ),
        migrations.RenameField(
            model_name='stockminimoproductos',
            old_name='stock_bul',
            new_name='min_bul',
        ),
        migrations.RenameField(
            model_name='stockminimoproductos',
            old_name='stock_mat',
            new_name='min_mat',
        ),
    ]
