# Generated by Django 3.2.3 on 2021-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211104_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_art', models.CharField(blank=True, max_length=100, null=True)),
                ('min_mat', models.IntegerField(blank=True, null=True)),
                ('min_bul', models.IntegerField(blank=True, null=True)),
                ('min_bod', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
